### ISSUE TITLE
The code you provided has a syntax error.

### ISSUE THREAD

**Issue by tallinn-learning** [LohurLaura/homework04#3]
https://github.com/LohurLaura/homework04/blob/0c15c4ab1a6868e914dc4a8b0a44210e65fc6118/src/NumberManipulator.java#L1C1-L8C2

methods are defined with curly braces {} to enclose the method body. Also, the semicolon ; after the method declaration should be replaced with an opening curly brace {. Here's the corrected version of your NumberManipulator class:

public class NumberManipulator {
    public int incrementByOne(int number) {
        number++;
        return number;
    }

    public int decrementByOne(int number) {
        number--;
        return number;
    }
}

The methods incrementByOne and decrementByOne have opening and closing curly braces, indicating the start and end of the method bodies.

Each method's code is indented inside the curly braces for readability.

The semicolon after the method declarations is replaced with an opening curly brace to define the method body.

**Comment by LohurLaura** [comment]
Corrected the code, thank you.
